# global:
#  scrape_interval: 15s
#  evaluation_interval: 15s


# scrape_configs:
# - job_name: 'api-gateway'
#  metrics_path: /actuator/prometheus
#  static_configs:
#  - targets: [ 'api-gateway:8080' ]


# - job_name: 'produk-service'
#  metrics_path: /actuator/prometheus
#  static_configs:
#  - targets: [ 'produk-service:8081' ]


# - job_name: 'order'
#  metrics_path: /actuator/prometheus
#  static_configs:
#  - targets: [ 'order:8083' ]


# - job_name: 'payment-service'
#  metrics_path: /actuator/prometheus
#  static_configs:
#  - targets: [ 'payment-service:8082' ]


# - job_name: 'customer-service'
#  metrics_path: /actuator/prometheus
#  static_configs:
#  - targets: [ 'customer-service:8084' ]


# # Jika menggunakan Node Exporter untuk host metrics
# - job_name: 'node-exporter'
#  static_configs:
#  - targets: [ 'node-exporter:9100' ]

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'produk-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['produk-service:8081']

  - job_name: 'booking-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['booking-service:9002']
      
  - job_name: 'order'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order:8083']

  - job_name: 'payment-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['payment-service:8082']

  - job_name: 'customer-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['customer-service:8084']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
