# apiVersion: v1
# kind: Service
# metadata:
#  name: grafana
# spec:
#  selector:
#    app: grafana
#  ports:
#  - protocol: TCP
#    port: 3000
#    targetPort: 3000
#  type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # nodePort: 30000  <-- DIHAPUS agar auto-assign port
