apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: hanifdinata/order:1.0.2
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: SPRING_APPLICATION_NAME
          value: "order"
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          value: "http://eurekaserver:8761/eureka/"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://mysql:3306/dbcommerce_orders?useSSL=false&serverTimezone=UTC"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "root_password"
      restartPolicy: Always
      imagePullSecrets:
      - name: mydockerhubsecret  # Jika image private, tambahkan ini
